extends Node

const ID = "HorseMod"
onready var Lure = get_node("/root/SulayreLure")

func _ready():
	
	Lure.assign_species_voice(ID, ID + ".species_horse", "mod://Sounds/neigh.ogg", "mod://Sounds/huff.ogg", "mod://Sounds/huff2.ogg")
	Lure.assign_face_animation(ID, ID + ".species_horse", "mod://Assets/horse_face.tres")
	Lure.assign_pattern_texture(ID, "pattern_calico", ID + ".species_horse", "mod://Assets/Textures/Patterns/callico.png")
	Lure.assign_pattern_texture(ID, "pattern_collie", ID + ".species_horse", "mod://Assets/Textures/Patterns/collie.png")
	Lure.assign_pattern_texture(ID, "pattern_spotted", ID + ".species_horse", "mod://Assets/Textures/Patterns/spot.png")
	Lure.assign_pattern_texture(ID, "pattern_tux", ID + ".species_horse", "mod://Assets/Textures/Patterns/tux.png")
	
	Lure.assign_pattern_texture(ID, ID + ".pattern_splash", ID + ".species_horse", "mod://Assets/Textures/Patterns/splash.png")
	Lure.assign_pattern_texture(ID, ID + ".pattern_tobiano", ID + ".species_horse", "mod://Assets/Textures/Patterns/tobiano.png")
	Lure.assign_pattern_texture(ID, ID + ".pattern_muzzle", ID + ".species_horse", "mod://Assets/Textures/Patterns/muzzle.png")
	Lure.assign_pattern_texture(ID, ID + ".pattern_snip", ID + ".species_horse", "mod://Assets/Textures/Patterns/snip.png")

	Lure.assign_cosmetic_mesh(ID, "accessory_antlers", ID + ".species_horse", "mod://Assets/AltMesh/antlers_horse.tres")
	Lure.assign_cosmetic_mesh(ID, "accessory_bandaid", ID + ".species_horse", "mod://Assets/AltMesh/bandaid_horse.tres")
	Lure.assign_cosmetic_mesh(ID, "accessory_cig", ID + ".species_horse", "mod://Assets/AltMesh/cig_horse.tres")
	Lure.assign_cosmetic_mesh(ID, "accessory_eyepatch", ID + ".species_horse", "mod://Assets/AltMesh/eyepatch_horse.tres")
	Lure.assign_cosmetic_mesh(ID, "accessory_glasses", ID + ".species_horse", "mod://Assets/AltMesh/glasses_horse.tres")
	Lure.assign_cosmetic_mesh(ID, "accessory_glasses_round", ID + ".species_horse", "mod://Assets/AltMesh/glasses_round_horse.tres")
	Lure.assign_cosmetic_mesh(ID, "accessory_monocle", ID + ".species_horse", "mod://Assets/AltMesh/monocle_horse.tres")
	Lure.assign_cosmetic_mesh(ID, "accessory_shades", ID + ".species_horse", "mod://Assets/AltMesh/shades_horse.tres")
	Lure.assign_cosmetic_mesh(ID, "accessory_shades_gold", ID + ".species_horse", "mod://Assets/AltMesh/shades_horse.tres")

	Lure.add_content(ID,"species_horse","mod://Resources/species_horse.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"shirt_cooler","mod://Resources/shirt_cooler.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"shirt_hungry","mod://Resources/shirt_hungry.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"shirt_pollo","mod://Resources/shirt_pollo.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	
	Lure.add_content(ID,"tail_donkey","mod://Resources/Tails/tail_donkey.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"tail_friesan","mod://Resources/Tails/tail_friesan.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"tail_horse","mod://Resources/Tails/tail_horse.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"tail_unicorn","mod://Resources/Tails/tail_unicorn.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	
	Lure.add_content(ID,"accessory_hooves_white","mod://Resources/Accessory/accessory_hooves_white.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"accessory_hooves_black","mod://Resources/Accessory/accessory_hooves_black.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"accessory_horn_curved_white","mod://Resources/Accessory/accessory_horn_curved_white.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"accessory_horn_curved_black","mod://Resources/Accessory/accessory_horn_curved_black.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"accessory_horn_white","mod://Resources/Accessory/accessory_horn_white.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"accessory_horn_black","mod://Resources/Accessory/accessory_horn_black.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"accessory_sagittarius_horns","mod://Resources/Accessory/accessory_sagittarius_horns.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	
	Lure.add_content(ID,"pattern_splash","mod://Resources/Patterns/pattern_splash.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"pattern_tobiano","mod://Resources/Patterns/pattern_tobiano.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"pattern_muzzle","mod://Resources/Patterns/pattern_muzzle.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"pattern_snip","mod://Resources/Patterns/pattern_snip.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])

	Lure.add_content(ID,"nose_horse","mod://Resources/nose_horse.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"nose_pony","mod://Resources/nose_pony.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])

	# Hey if you're using this for an example of how to do a species, please use a for loop for this
	# I do it slow and stupid, please don't replicate my methods, they're bad

	Lure.assign_cosmetic_mesh(ID, ID + ".beard_black", ID + ".species_horse", "mod://Assets/beard.tres")
	Lure.assign_cosmetic_mesh(ID, ID + ".beard_blue", ID + ".species_horse", "mod://Assets/beard.tres")
	Lure.assign_cosmetic_mesh(ID, ID + ".beard_brown", ID + ".species_horse", "mod://Assets/beard.tres")
	Lure.assign_cosmetic_mesh(ID, ID + ".beard_green", ID + ".species_horse", "mod://Assets/beard.tres")
	Lure.assign_cosmetic_mesh(ID, ID + ".beard_grey", ID + ".species_horse", "mod://Assets/beard.tres")
	Lure.assign_cosmetic_mesh(ID, ID + ".beard_maroon", ID + ".species_horse", "mod://Assets/beard.tres")
	Lure.assign_cosmetic_mesh(ID, ID + ".beard_midnight", ID + ".species_horse", "mod://Assets/beard.tres")
	Lure.assign_cosmetic_mesh(ID, ID + ".beard_olive", ID + ".species_horse", "mod://Assets/beard.tres")
	Lure.assign_cosmetic_mesh(ID, ID + ".beard_orange", ID + ".species_horse", "mod://Assets/beard.tres")
	Lure.assign_cosmetic_mesh(ID, ID + ".beard_pink", ID + ".species_horse", "mod://Assets/beard.tres")
	Lure.assign_cosmetic_mesh(ID, ID + ".beard_purple", ID + ".species_horse", "mod://Assets/beard.tres")
	Lure.assign_cosmetic_mesh(ID, ID + ".beard_red", ID + ".species_horse", "mod://Assets/beard.tres")
	Lure.assign_cosmetic_mesh(ID, ID + ".beard_salmon", ID + ".species_horse", "mod://Assets/beard.tres")
	Lure.assign_cosmetic_mesh(ID, ID + ".beard_stone", ID + ".species_horse", "mod://Assets/beard.tres")
	Lure.assign_cosmetic_mesh(ID, ID + ".beard_tan", ID + ".species_horse", "mod://Assets/beard.tres")
	Lure.assign_cosmetic_mesh(ID, ID + ".beard_teal", ID + ".species_horse", "mod://Assets/beard.tres")
	Lure.assign_cosmetic_mesh(ID, ID + ".beard_white", ID + ".species_horse", "mod://Assets/beard.tres")
	Lure.assign_cosmetic_mesh(ID, ID + ".beard_yellow", ID + ".species_horse", "mod://Assets/beard.tres")

	Lure.add_content(ID,"beard_black","mod://Resources/Beard/beard_black.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"beard_blue","mod://Resources/Beard/beard_blue.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"beard_brown","mod://Resources/Beard/beard_brown.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"beard_green","mod://Resources/Beard/beard_green.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"beard_grey","mod://Resources/Beard/beard_grey.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"beard_maroon","mod://Resources/Beard/beard_maroon.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"beard_midnight","mod://Resources/Beard/beard_midnight.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"beard_olive","mod://Resources/Beard/beard_olive.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"beard_orange","mod://Resources/Beard/beard_orange.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"beard_pink","mod://Resources/Beard/beard_pink.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"beard_purple","mod://Resources/Beard/beard_purple.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"beard_red","mod://Resources/Beard/beard_red.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"beard_salmon","mod://Resources/Beard/beard_salmon.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"beard_stone","mod://Resources/Beard/beard_stone.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"beard_tan","mod://Resources/Beard/beard_tan.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"beard_teal","mod://Resources/Beard/beard_teal.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"beard_white","mod://Resources/Beard/beard_white.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"beard_yellow","mod://Resources/Beard/beard_yellow.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])

	Lure.add_content(ID,"hair_curly_black","mod://Resources/Hair/Curly/hair_curly_black.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_curly_blue","mod://Resources/Hair/Curly/hair_curly_blue.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_curly_brown","mod://Resources/Hair/Curly/hair_curly_brown.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_curly_green","mod://Resources/Hair/Curly/hair_curly_green.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_curly_grey","mod://Resources/Hair/Curly/hair_curly_grey.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_curly_maroon","mod://Resources/Hair/Curly/hair_curly_maroon.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_curly_midnight","mod://Resources/Hair/Curly/hair_curly_midnight.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_curly_olive","mod://Resources/Hair/Curly/hair_curly_olive.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_curly_orange","mod://Resources/Hair/Curly/hair_curly_orange.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_curly_pink","mod://Resources/Hair/Curly/hair_curly_pink.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_curly_purple","mod://Resources/Hair/Curly/hair_curly_purple.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_curly_red","mod://Resources/Hair/Curly/hair_curly_red.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_curly_salmon","mod://Resources/Hair/Curly/hair_curly_salmon.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_curly_stone","mod://Resources/Hair/Curly/hair_curly_stone.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_curly_tan","mod://Resources/Hair/Curly/hair_curly_tan.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_curly_teal","mod://Resources/Hair/Curly/hair_curly_teal.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_curly_white","mod://Resources/Hair/Curly/hair_curly_white.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_curly_yellow","mod://Resources/Hair/Curly/hair_curly_yellow.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])

	Lure.add_content(ID,"hair_emo_black","mod://Resources/Hair/Emo/hair_emo_black.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_emo_blue","mod://Resources/Hair/Emo/hair_emo_blue.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_emo_brown","mod://Resources/Hair/Emo/hair_emo_brown.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_emo_green","mod://Resources/Hair/Emo/hair_emo_green.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_emo_grey","mod://Resources/Hair/Emo/hair_emo_grey.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_emo_maroon","mod://Resources/Hair/Emo/hair_emo_maroon.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_emo_midnight","mod://Resources/Hair/Emo/hair_emo_midnight.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_emo_olive","mod://Resources/Hair/Emo/hair_emo_olive.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_emo_orange","mod://Resources/Hair/Emo/hair_emo_orange.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_emo_pink","mod://Resources/Hair/Emo/hair_emo_pink.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_emo_purple","mod://Resources/Hair/Emo/hair_emo_purple.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_emo_red","mod://Resources/Hair/Emo/hair_emo_red.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_emo_salmon","mod://Resources/Hair/Emo/hair_emo_salmon.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_emo_stone","mod://Resources/Hair/Emo/hair_emo_stone.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_emo_tan","mod://Resources/Hair/Emo/hair_emo_tan.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_emo_teal","mod://Resources/Hair/Emo/hair_emo_teal.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_emo_white","mod://Resources/Hair/Emo/hair_emo_white.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_emo_yellow","mod://Resources/Hair/Emo/hair_emo_yellow.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])

	Lure.add_content(ID,"hair_mohawk_black","mod://Resources/Hair/Mohawk/hair_mohawk_black.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mohawk_blue","mod://Resources/Hair/Mohawk/hair_mohawk_blue.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mohawk_brown","mod://Resources/Hair/Mohawk/hair_mohawk_brown.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mohawk_green","mod://Resources/Hair/Mohawk/hair_mohawk_green.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mohawk_grey","mod://Resources/Hair/Mohawk/hair_mohawk_grey.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mohawk_maroon","mod://Resources/Hair/Mohawk/hair_mohawk_maroon.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mohawk_midnight","mod://Resources/Hair/Mohawk/hair_mohawk_midnight.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mohawk_olive","mod://Resources/Hair/Mohawk/hair_mohawk_olive.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mohawk_orange","mod://Resources/Hair/Mohawk/hair_mohawk_orange.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mohawk_pink","mod://Resources/Hair/Mohawk/hair_mohawk_pink.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mohawk_purple","mod://Resources/Hair/Mohawk/hair_mohawk_purple.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mohawk_red","mod://Resources/Hair/Mohawk/hair_mohawk_red.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mohawk_salmon","mod://Resources/Hair/Mohawk/hair_mohawk_salmon.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mohawk_stone","mod://Resources/Hair/Mohawk/hair_mohawk_stone.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mohawk_tan","mod://Resources/Hair/Mohawk/hair_mohawk_tan.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mohawk_teal","mod://Resources/Hair/Mohawk/hair_mohawk_teal.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mohawk_white","mod://Resources/Hair/Mohawk/hair_mohawk_white.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mohawk_yellow","mod://Resources/Hair/Mohawk/hair_mohawk_yellow.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])

	Lure.add_content(ID,"hair_mane_black","mod://Resources/Hair/Mane/hair_mane_black.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mane_blue","mod://Resources/Hair/Mane/hair_mane_blue.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mane_brown","mod://Resources/Hair/Mane/hair_mane_brown.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mane_green","mod://Resources/Hair/Mane/hair_mane_green.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mane_grey","mod://Resources/Hair/Mane/hair_mane_grey.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mane_maroon","mod://Resources/Hair/Mane/hair_mane_maroon.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mane_midnight","mod://Resources/Hair/Mane/hair_mane_midnight.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mane_olive","mod://Resources/Hair/Mane/hair_mane_olive.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mane_orange","mod://Resources/Hair/Mane/hair_mane_orange.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mane_pink","mod://Resources/Hair/Mane/hair_mane_pink.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mane_purple","mod://Resources/Hair/Mane/hair_mane_purple.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mane_red","mod://Resources/Hair/Mane/hair_mane_red.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mane_salmon","mod://Resources/Hair/Mane/hair_mane_salmon.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mane_stone","mod://Resources/Hair/Mane/hair_mane_stone.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mane_tan","mod://Resources/Hair/Mane/hair_mane_tan.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mane_teal","mod://Resources/Hair/Mane/hair_mane_teal.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mane_white","mod://Resources/Hair/Mane/hair_mane_white.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
	Lure.add_content(ID,"hair_mane_yellow","mod://Resources/Hair/Mane/hair_mane_yellow.tres",[Lure.LURE_FLAGS.FREE_UNLOCK])
